name: deploying with docker script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on EC2
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

        #log in to docker
      - name: log in the docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ci-cd101:latest

      - name: Deploy docker images to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          #ssh into the ec2
          port: 22
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/ci-cd101:latest
            sudo docker stop ci-cd101 || true
            sudo docker rm ci-cd101 || true
            sudo docker run -d --name ci-cd101 -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/ci-cd101:latest
